### PR TITLE
fix: verifyIsOnPage() should throw for nonexistent elements (#130)

### LINKED ISSUE #130: verifyIsOnPage() not throwing error when passing a nonexistent element
# Bug
When calling verifyIsOnPage() with a nonexistent element, the lookup fails but then the test continues
In BasePage.verifyIsOnPage() we see:
```
    // Wait until the page is loaded then look for the elements
    var isPageLoaded = getAutomationWait().waitUntilPageIsLoaded();
    if (isPageLoaded) {
      listOfElements.forEach(elementOnPage -> {
        try {
          elementOnPage.isDisplayed();
        } catch (TimeoutException e) {
          throw new TimeoutException(
              String.format("Page verification failed. Could not find the element " +
                  "%s for the intended page: %s", elementOnPage, getClass().getSimpleName()));
        }
      });
```
and in BaseWebElement:
```
  public boolean isDisplayed() {
    try {
      var element = getRawWebElement();
      return element != null && element.isDisplayed();
    } catch (WebDriverException e) {
      return false;
    }
  }
```

I think the issue is that the WebDriverException here is being caught, and the return value of elementOnPage.isDisplayed() is never being verified.

# Expected
A TimeoutException should be thrown and the test execution should stop

# Repro

```
package com.demo;

import io.github.kgress.scaffold.BasePage;
import io.github.kgress.scaffold.webelements.DivWebElement;
import lombok.Getter;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.TimeoutException;

import static org.junit.jupiter.api.Assertions.assertThrows;

class MyTest extends BaseTest {
  @Test
  void demo() {
    getWebDriverWrapper().get("https://www.saucedemo.com");
    assertThrows(TimeoutException.class, Demo::new);
  }

  @Getter
  class Demo extends BasePage {
    private final DivWebElement nonexistent = new DivWebElement("#nonexistent #element");
    public Demo() { verifyIsOnPage(getNonexistent()); }
  }
}
```

### PR DESCRIPTION
**Pull request by atari-xia**
- checks return value if isDisplayed() in verifyIsOnPage()
closes #130

### CODE REVIEW

File: framework/src/main/java/io/github/kgress/scaffold/BasePage.java [hunk 1]
```diff
@@ -67,7 +67,9 @@ protected Boolean verifyIsOnPage(BaseWebElement... element) {
     if (isPageLoaded) {
       listOfElements.forEach(elementOnPage -> {
         try {
-          elementOnPage.isDisplayed();
+          if (!elementOnPage.isDisplayed()) {
+            throw new TimeoutException();
+          }
```
Comment (kgress) [inline framework/src/main/java/io/github/kgress/scaffold/BasePage.java:72]: Could you consolidate the entire lambda from line 69 to 78 with the following:
```
if (!elementOnPage.isDisplayed()) {
          throw new TimeoutException(String.format("Page verification failed. Could not find the element " +
              "%s for the intended page: %s", elementOnPage, getClass().getSimpleName()));
        }
      });
```

**Review by kgress — CHANGES_REQUESTED** [review]
Nice catch. It looks my unit testing was written poorly, to always mock return an exception instead of just return false. The unit test didn't catch the change I made to `isDiplayed()` not returning an exception, and instead only returning false if the element isn't displayed.

In addition to the comment I added for the file, could you also update the `elementsNotDisplayed()` tests on `BasePageTests` with the following:
```
@Test
    public void verifyIsOnPage_elementNotDisplayed() {
        when(mockAutomationWait.waitUntilPageIsLoaded()).thenReturn(true);
        when(mockDivWebElement.isDisplayed()).thenReturn(false);
        var exception = assertThrows(TimeoutException.class, () ->
                testBasePage.verifyIsOnPage_callProtectedMethod(mockDivWebElement));
        assertTrue(exception.getMessage().contains(EXPECTED_FAILED_TEXT));
    }

    @Test
    public void verifyIsOnPage_elementsNotDisplayed() {
        when(mockAutomationWait.waitUntilPageIsLoaded()).thenReturn(true);
        when(mockDivWebElement.isDisplayed()).thenReturn(true);
        when(mockInputWebElement.isDisplayed()).thenReturn(false);
        var exception = assertThrows(TimeoutException.class, () ->
                testBasePage.verifyIsOnPage_callProtectedMethod(mockDivWebElement, mockInputWebElement));
        assertTrue(exception.getMessage().contains(EXPECTED_FAILED_TEXT));
    }
```

**Review by kgress — APPROVED** [review]
